# Generated by Django 4.1.7 on 2023-03-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
