# Generated by Django 4.1.7 on 2023-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_author_born_location_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(default='No data', max_length=3000),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(default='No data', max_length=10000),
        ),
    ]
